### ISSUE TITLE
Use of exec() in setup.py

### ISSUE THREAD

**Issue by Pascal-0x90** [cisagov/findcdn#18]
# Proposal

The use of `exec` can be dangerous potentially allowing execution of python code on a system. 

## Motivation

The codebase should more strictly follow Python convention to hopefully improve maintainability.

## Details

Since this is the `setup.py` script, it may not need to be addressed as we assume this is something that will be deployed by the user and does not pose an immediate risk to the operation of the tool. This could/should be mitigated at some point to not use exec. The specific code is mentioned below:
https://github.com/cisagov/findcdn/blob/46073ffbe9bffcdd3f76173356afeae22521eabe/setup.py#L29

**Comment by mcdonnnj** [comment]
This is inherited from [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library), so I would kick the issue up the chain.

**Comment by S4lt5** [comment]
https://github.com/cisagov/skeleton-python-library/blob/develop/setup.py has indeed updated and removed this truly bizarre way to read a version string

**Comment by Pascal-0x90** [comment]
Closing since this has been fixed!
